### ISSUE TITLE
Building proceedings without papers

### ISSUE THREAD

**Issue by danielhers** [rycolab/aclpub2#126]
Some workshops have no papers but still want proceedings with invited talks abstracts and schedule.
However, when `papers.yml` is empty, they get [this error](https://github.com/emnlp-2022/SSLL/actions/runs/3491907520/jobs/5845088039):
```
Traceback (most recent call last):
  File "aclpub2/bin/generate", line 40, in <module>
    generate_proceedings(args.path, args.overwrite, args.outdir)
  File "/home/runner/work/SSLL/SSLL/aclpub2/aclpub2/generate.py", line 45, in generate_proceedings
    ) = load_configs(root)
  File "/home/runner/work/SSLL/SSLL/aclpub2/aclpub2/config.py", line 25, in load_configs
    for paper in papers:
TypeError: 'NoneType' object is not iterable
```

**Comment by zhzhang** [comment]
On it.
