### ISSUE TITLE
generaty.py fails without --overwrite

### ISSUE THREAD

**Issue by habernal** [rycolab/aclpub2#178]
Repro:
```bash
$ ./bin/generate examples/sigdial --proceedings
[...]
Traceback (most recent call last):
  File "/home/habi/PycharmProjects/aclpub2/./bin/generate", line 50, in <module>
    generate_proceedings(args.path, args.overwrite, args.outdir, args.nopax, args.frontmatter)
  File "/home/habi/PycharmProjects/aclpub2/aclpub2/generate.py", line 27, in generate_proceedings
    raise Exception(
Exception: Build directory build is not empty, and the overwrite flag is false.
```
even if the `built` dir did not exist.

```bash
$ python --version
Python 3.12.3
```

**Comment by g-jing** [comment]
Hi Ivan. We also have this issue. Could you share your solution? Thanks!

**Comment by habernal** [comment]
Sure, again see the linked PR: https://github.com/rycolab/aclpub2/pull/179
and the diff https://github.com/rycolab/aclpub2/pull/179/files

or just use `--overwrite` always as a parameter
