### ISSUE TITLE
Error NoneType object is not iterable

### ISSUE THREAD

**Issue by bharathichezhiyan** [rycolab/aclpub2#67]
./bin/generate examples/sigdial --proceedings --handbook

Traceback (most recent call last):
  File "/home/bharathi/Desktop/aclpub2/./bin/generate", line 32, in <module>
    generate_handbook(args.path, args.overwrite)
  File "/home/bharathi/Desktop/aclpub2/aclpub2/generate.py", line 176, in generate_handbook
    ) = load_configs_handbook(root)
  File "/home/bharathi/Desktop/aclpub2/aclpub2/generate.py", line 573, in load_configs_handbook
    for workshop in workshops:
TypeError: 'NoneType' object is not iterable

**Comment by crux82** [comment]
It seems that you are trying ti build Aldo the booklet. Do you really need It?

If not, you should onlu use 

./bin/generate examples/sigdial --proceedings

**Comment by bharathichezhiyan** [comment]
Thanks it worked with ./bin/generate examples/sigdial --proceedings --overwrite
